### ISSUE TITLE
Collision detection not taking into account extension

### ISSUE THREAD

**Issue by xluxeq** [ragibson/media-gallery-compressor#1]
Collision detection not taking into account extension

**Comment by ragibson** [comment]
This is intentional because the compression will change the file extension in general.

E.g., `video.mp4` and `video.mov` would collide since they'd both become `video_compressed.mp4`.

**Comment by ragibson** [comment]
Also note that we'll change the image file extension if it turns out to be incorrect. 

So if `image.jpg` is actually a PNG file, it will become `image_compressed.png`. There are a few comments in the codebase discussing these quirks.
