### ISSUE TITLE
Does not work on command prompt

### ISSUE THREAD

**Issue by mizu-048** [ragibson/media-gallery-compressor#2]
![image](https://github.com/user-attachments/assets/6ea9b770-816d-4455-9ef8-83cb1bbdc422)
tried the same command on both cmd and pwsh 7
works on only powershell
i also tried in various other formats like 
`"D:\\compres_OUT"`
`'D:\\compres_OUT'`
`'D:\compres_OUT`

**Comment by ragibson** [comment]
This is not a bug -- you've escaped your own quote and passed `D:\compres_IN" -o D:\compres_OUT` as a single argument.

**Comment by ragibson** [comment]
See [Why does trailing backslash followed by quote behave so strangely in cmd?](https://stackoverflow.com/questions/41607045/why-does-trailing-backslash-followed-by-quote-behave-so-strangely-in-cmd) for more background on this Windows behavior.
